### PR TITLE
Expand data fetching to include beacons from the beaconSets section #165

### LINKED ISSUE #165: Expand data fetching to include beacons from the `beaconSets` section

### PR DESCRIPTION
**Pull request by acenolaza**
Closes #165

### CODE REVIEW

**Review by aquarat — APPROVED** [review]
Looks great to me :)
De-duplication of beacon ID update assessment is elegant.

**Comment by acenolaza** [comment]
> Looks great to me :) De-duplication of beacon ID update assessment is elegant.

I have to give the credit to @Siegrift for that since I started by using `Array.from(new Set([...beconIds, ...beaconSetsBeaconIds]))` but then I saw he was using `lodash/uniq` on another file :)

**Review by Siegrift — APPROVED** [review]
👍 LGTM

Btw. you could have based this PR onto https://github.com/API3-CTT/airseeker/pull/174

**Comment by acenolaza** [comment]
> +1 LGTM
> 
> Btw. you could have based this PR onto #174

I did 😕 but I might have selected the wrong base branch when creating the PR

**Pull request merged**
