### PR TITLE
Update missing value alert

### LINKED ISSUE #500: [Airseeker Telemetry]: Swap out/remove error message Nodary reference
See https://api3workspace.slack.com/archives/C05RMQJ3X2L/p1701179579012749?thread_ts=1701177769.730009&cid=C05RMQJ3X2L

The Airseeker Telemetry variant creates OpsGenie alerts citing "Nodary" when it's referring to reference datafeed values. This is actually incorrect and confuses Nodary respondents (Bedirhan). It should say something else when referring to these reference values, possibly "API Analysis" or perhaps just remove the Nodary name entirely.

Probably name it "API-Analysis" or "reference data provider".

### PR DESCRIPTION
**Pull request by vponline**
Closes [[Airseeker Telemetry]: Swap out/remove error message Nodary reference#500](https://github.com/api3dao/airseeker/issues/500)

### CODE REVIEW

**Comment by bdrhn9** [comment]
There are lots of place still Nodary naming populated here some examples:

- https://github.com/api3dao/airseeker/blob/8267a3c95e964d2763f9ab7adea800129dbc6d6d/src/alerting.ts#L125
- https://github.com/api3dao/airseeker/blob/8267a3c95e964d2763f9ab7adea800129dbc6d6d/src/alerting.ts#L350
- https://github.com/api3dao/airseeker/blob/8267a3c95e964d2763f9ab7adea800129dbc6d6d/src/alerting.ts#L377


Also in my opinion variables named as `*nodary*` that refers reference data should be changed. I don't think variable name changed is urgent but the alerts are.

**Comment by vponline** [comment]
I see thanks, I will go through the rest of the alerts as well then 😄

**Review by aquarat — CHANGES_REQUESTED** [review]
Looks fine 😆 but related to Bedirhan's comment it's probably safe to do a project-wide replace of nodary with maybe "source" 🤷 ?

**Comment by vponline** [comment]
> Looks fine 😆 but related to Bedirhan's comment it's probably safe to do a project-wide replace of nodary with maybe "source" 🤷 ?

We could almost do this, there are a few db column names still containing nodary, but that should be ok.

**Comment by aquarat** [comment]
I'll try and deploy this and see what happens, can always revert.

(update) Deployed... now we wait ~a day.

**Comment by aquarat** [comment]
No errors and/or issues, so this is running nicely.

**Pull request merged**
