### PR TITLE
Tighten update conditions according to changes in the Api3ServerV1

### LINKED ISSUE #351: Tighten update conditions according to changes in the Api3ServerV1
Refer to [#113](https://github.com/api3dao/airnode-protocol-v1/pull/113)

### PR DESCRIPTION
**Pull request by bdrhn9**
Closes #351 

- Updated airnode-protocol-v1 package to version 1.1.2
- ~~Added new update condition that checks value of fulfillment data is changed compared to on-chain record~~
- Because the feature `updating Beacon sets with signed data` is deprecated,  I refactored the current implementation to use the function `updateBeaconSetWithBeacons`.  Even though this implementation is working under e2e test, it is probably incomplete. Instead of removing Beacon set updates, I did this refactoring, because it'll be helpful while we are updating the function `updateBeaconSets` in near future.
- Refactored e2e tests not to use deprecated update protocol PSP which is used while initializing test beacons
- Renamed `DapiServer` to `Api3ServerV1`, thanks a lot @acenolaza

### CODE REVIEW

**Comment by acenolaza** [comment]
> * Didn't changed variable names `dapiServer` to `api3ServerV1`, this may be another issue or maybe we don't want to do this renaming?

I think we do since we'll no longer interact directly with DapiServer but with Api3ServerV1 contract from now on. I've applied changes [here](https://github.com/api3dao/airseeker/pull/352/commits/76ff4a62aebbbc798371e5c11942bd3f237bfd84) since it's pretty straightforward

**Review by acenolaza — APPROVED** [review]
LGTM 🔥

I **think** we are rolling back the protocol changes up to [this](https://github.com/api3dao/airnode-protocol-v1/commit/f2ae9e7e8b2205e8f83ab26c8e41f5de488da5e7) commit

**Comment by bdrhn9** [comment]
@acenolaza Lots of thanks for helping me to rename DapiServer -> Api3ServerV1. 

Solved the e2e error. This is because adminRoleDescription is changed from `DapiServer admin` to `Api3ServerV1 admin`, address for the contract (apiServerV1) is changed. 

Imo, it'd be better to merge this PR, after https://github.com/api3dao/airnode-protocol-v1 is rolled back and new npm package is published.

**Comment by acenolaza** [comment]
> after https://github.com/api3dao/airnode-protocol-v1 is rolled back and new npm package is published

Changes [have been rolled back](https://github.com/api3dao/airnode-protocol-v1/pull/116) so I guess all we need now is a new npm package to be published and start testing Airseeker using the new contracts 🚀 (Assuming that contracts have also been re-deployed)

**Comment by bdrhn9** [comment]
> > after https://github.com/api3dao/airnode-protocol-v1 is rolled back and new npm package is published
> 
> Changes [have been rolled back](https://github.com/api3dao/airnode-protocol-v1/pull/116) so I guess all we need now is a new npm package to be published and start testing Airseeker using the new contracts rocket (Assuming that contracts have also been re-deployed)

Contract factories are missing in new package v1.2.2. I notified Burak about this issue. After this issue was solved, we can merge this.  I used lots of `after` condition during this PR 😄

**Pull request merged**
